set VCPKG_ROOT=E:/vcpkg/installed/x64-windows
set VCPKG_DIR=E:/vcpkg
set CMAKE_MODULE_PATH=%VCPKG_ROOT%/share/sfgui/;E:/projects/SchiffbruchEngine/cmake/
set CMAKE_TOOLCHAIN_FILE=%VCPKG_DIR%/scripts/buildsystems/vcpkg.cmake
set CMAKE_INSTALL_PREFIX=%VCPKG_ROOT%

cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=%CMAKE_TOOLCHAIN_FILE% -DCMAKE_MODULE_PATH=%CMAKE_MODULE_PATH% -DCMAKE_INSTALL_PREFIX=%CMAKE_INSTALL_PREFIX% -DSFML_ROOT="%VCPKG_ROOT%/" -DSFGUI_ROOT="%VCPKG_ROOT%/" -DBOOST_ROOT="%VCPKG_ROOT%/" -DGLM_ROOT_DIR="%VCPKG_ROOT%/" ..